# Generated by Django 5.1.4 on 2025-10-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_lat', models.FloatField(default=12.9716)),
                ('default_lon', models.FloatField(default=77.5946)),
            ],
        ),
    ]
