# Generated by Django 5.1.4 on 2025-10-22 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_code', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('place_name', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('owm_condition_id', models.IntegerField(blank=True, null=True)),
                ('owm_condition', models.CharField(blank=True, max_length=128)),
                ('owm_temp_c', models.FloatField(blank=True, null=True)),
                ('owm_precip_mm', models.FloatField(blank=True, null=True)),
                ('weather_tag', models.CharField(blank=True, default='any', max_length=16)),
                ('provider', models.CharField(blank=True, default='openweathermap', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'table_code')},
            },
        ),
    ]
