# Generated by Django 5.1.4 on 2025-10-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_locationselection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationselection',
            old_name='weather_tag',
            new_name='om_condition_tag',
        ),
        migrations.RenameField(
            model_name='locationselection',
            old_name='owm_precip_mm',
            new_name='om_precip_mm',
        ),
        migrations.RenameField(
            model_name='locationselection',
            old_name='owm_temp_c',
            new_name='om_temp_c',
        ),
        migrations.RenameField(
            model_name='locationselection',
            old_name='owm_condition_id',
            new_name='om_weather_code',
        ),
        migrations.RemoveField(
            model_name='locationselection',
            name='owm_condition',
        ),
        migrations.AlterField(
            model_name='locationselection',
            name='provider',
            field=models.CharField(default='open-meteo', max_length=32),
        ),
    ]
