# Generated by Django 5.1.4 on 2025-10-22 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_weather_tag_locationselection_om_condition_tag_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationSelection',
        ),
    ]
