# Generated by Django 5.1.4 on 2025-10-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_locationselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('region', models.CharField(choices=[('Cold', 'Cold Regions / Hill Stations'), ('HotDry', 'Hot & Dry Regions'), ('Coastal', 'Moderate / Coastal Regions'), ('Central', 'Central / Plateau Regions'), ('EastNE', 'Eastern & North-Eastern Regions'), ('South', 'Southern Tropical Regions'), ('UT', 'Union Territories'), ('Other', 'Other')], default='Other', max_length=16)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['region', 'name'],
            },
        ),
    ]
