# Generated by Django 5.1.4 on 2025-10-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='payment_qr/')),
                ('payment_link', models.URLField(blank=True, help_text="Optional: where 'Open Payment URL' should go", null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
