# Generated by Django 5.0.3 on 2026-05-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sitepayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dynamic_pricing_enabled", models.BooleanField(default=False)),
                (
                    "surge_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                ("last_inventory_order", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
