# Generated by Django 5.1.4 on 2025-10-21 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('dessert', 'Dessert')], default='food', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('any', 'Any'), ('hot', 'Hot day'), ('cold', 'Cold day'), ('rain', 'Rainy'), ('clear', 'Clear/Normal')], default='any', max_length=16)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='menu.item')),
            ],
        ),
    ]
