# Generated by Django 5.0.3 on 2026-05-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_prepared_at_orderitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="weather_condition",
            field=models.CharField(
                blank=True,
                help_text="Weather condition at the time of order",
                max_length=50,
                null=True,
            ),
        ),
    ]
